[package]
name = "cargo-emanate"
version = "0.1.3"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/aspectron/cargo-emanate"
keywords = ["cargo", "subcommand", "installation", "package"]
categories = ["command-line-utilities", "development-tools::cargo-plugins", "development-tools::build-utils"]
exclude = ["/.*", "/test"]
description = """
Cargo subcommand for multi-repository management and creation of application packages.
"""

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
duct = "0.13.5"
toml = "0.5.9"
tokio = { version = "1.20.1", features = ["full"] }
serde = "1.0.97"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
async-std = "1.12.0"
console = "0.15.0"

