[package]
name = "cargo-emanate"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
duct = "0.13.5"
toml = "0.5.9"
tokio = { version = "1.20.1", features = ["full"] }
serde = "1.0.97"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
async-std = "1.12.0"

